// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/assistant/data/models/chat_thread_box.dart';
import 'features/context/domain/entities/document_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7035140778498044880),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(6, 8797849819853913992),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7064351884726495478),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 844416050715275806),
        name: 'documentTitle',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 8853101028003422256),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5454680228921093032),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5504691566618570443),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2117751560864178643),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8797849819853913992),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 4410574472035736354),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7514555814550740785),
    name: 'ChatMessageBox',
    lastPropertyId: const obx_int.IdUid(7, 6370828985791541420),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6778601470025593426),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 92122755749263985),
        name: 'messageId',
        type: 9,
        flags: 40,
        indexId: const obx_int.IdUid(3, 6694302986667370828),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4656265583605660482),
        name: 'threadId',
        type: 9,
        flags: 8,
        indexId: const obx_int.IdUid(4, 4498975362721733583),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8193788032881072146),
        name: 'role',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5946273438667772289),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3643120505869524499),
        name: 'thinking',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6370828985791541420),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2329032265644042887),
    name: 'ChatThreadBox',
    lastPropertyId: const obx_int.IdUid(8, 4105221145724707902),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8377725080285235349),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1096411176014836760),
        name: 'threadId',
        type: 9,
        flags: 40,
        indexId: const obx_int.IdUid(5, 8319162824871040312),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 464179234006644623),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7245498532030590122),
        name: 'systemInstruction',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4051714762867169412),
        name: 'chatFamily',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7967932845817016510),
        name: 'modelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3510898924227377693),
        name: 'createdAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4105221145724707902),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 2329032265644042887),
    lastIndexId: const obx_int.IdUid(5, 8319162824871040312),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[0],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final documentTitleOffset = fbb.writeString(object.documentTitle);
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, documentTitleOffset);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.chunkIndex);
        fbb.addInt64(4, object.createdAtMs);
        fbb.addOffset(5, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final documentTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final chunkIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = DocumentChunk(
          documentTitle: documentTitleParam,
          text: textParam,
          chunkIndex: chunkIndexParam,
          createdAtMs: createdAtMsParam,
          id: idParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    ChatMessageBox: obx_int.EntityDefinition<ChatMessageBox>(
      model: _entities[1],
      toOneRelations: (ChatMessageBox object) => [],
      toManyRelations: (ChatMessageBox object) => {},
      getId: (ChatMessageBox object) => object.id,
      setId: (ChatMessageBox object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageBox object, fb.Builder fbb) {
        final messageIdOffset = fbb.writeString(object.messageId);
        final threadIdOffset = fbb.writeString(object.threadId);
        final textOffset = fbb.writeString(object.text);
        final thinkingOffset = fbb.writeString(object.thinking);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageIdOffset);
        fbb.addOffset(2, threadIdOffset);
        fbb.addInt64(3, object.role);
        fbb.addOffset(4, textOffset);
        fbb.addOffset(5, thinkingOffset);
        fbb.addInt64(6, object.createdAtMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final threadIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final roleParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final thinkingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = ChatMessageBox(
          messageId: messageIdParam,
          threadId: threadIdParam,
          role: roleParam,
          text: textParam,
          createdAtMs: createdAtMsParam,
          thinking: thinkingParam,
          id: idParam,
        );

        return object;
      },
    ),
    ChatThreadBox: obx_int.EntityDefinition<ChatThreadBox>(
      model: _entities[2],
      toOneRelations: (ChatThreadBox object) => [],
      toManyRelations: (ChatThreadBox object) => {},
      getId: (ChatThreadBox object) => object.id,
      setId: (ChatThreadBox object, int id) {
        object.id = id;
      },
      objectToFB: (ChatThreadBox object, fb.Builder fbb) {
        final threadIdOffset = fbb.writeString(object.threadId);
        final titleOffset = fbb.writeString(object.title);
        final systemInstructionOffset = fbb.writeString(
          object.systemInstruction,
        );
        final chatFamilyOffset = fbb.writeString(object.chatFamily);
        final modelIdOffset = object.modelId == null
            ? null
            : fbb.writeString(object.modelId!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, threadIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, systemInstructionOffset);
        fbb.addOffset(4, chatFamilyOffset);
        fbb.addOffset(5, modelIdOffset);
        fbb.addInt64(6, object.createdAtMs);
        fbb.addInt64(7, object.updatedAtMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final threadIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final systemInstructionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final chatFamilyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final modelIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = ChatThreadBox(
          threadId: threadIdParam,
          title: titleParam,
          systemInstruction: systemInstructionParam,
          chatFamily: chatFamilyParam,
          createdAtMs: createdAtMsParam,
          updatedAtMs: updatedAtMsParam,
          modelId: modelIdParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[0],
  );

  /// See [DocumentChunk.documentTitle].
  static final documentTitle = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[1],
  );

  /// See [DocumentChunk.text].
  static final text = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[2],
  );

  /// See [DocumentChunk.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[3],
  );

  /// See [DocumentChunk.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[4],
  );

  /// See [DocumentChunk.embedding].
  static final embedding = obx.QueryHnswProperty<DocumentChunk>(
    _entities[0].properties[5],
  );
}

/// [ChatMessageBox] entity fields to define ObjectBox queries.
class ChatMessageBox_ {
  /// See [ChatMessageBox.id].
  static final id = obx.QueryIntegerProperty<ChatMessageBox>(
    _entities[1].properties[0],
  );

  /// See [ChatMessageBox.messageId].
  static final messageId = obx.QueryStringProperty<ChatMessageBox>(
    _entities[1].properties[1],
  );

  /// See [ChatMessageBox.threadId].
  static final threadId = obx.QueryStringProperty<ChatMessageBox>(
    _entities[1].properties[2],
  );

  /// See [ChatMessageBox.role].
  static final role = obx.QueryIntegerProperty<ChatMessageBox>(
    _entities[1].properties[3],
  );

  /// See [ChatMessageBox.text].
  static final text = obx.QueryStringProperty<ChatMessageBox>(
    _entities[1].properties[4],
  );

  /// See [ChatMessageBox.thinking].
  static final thinking = obx.QueryStringProperty<ChatMessageBox>(
    _entities[1].properties[5],
  );

  /// See [ChatMessageBox.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<ChatMessageBox>(
    _entities[1].properties[6],
  );
}

/// [ChatThreadBox] entity fields to define ObjectBox queries.
class ChatThreadBox_ {
  /// See [ChatThreadBox.id].
  static final id = obx.QueryIntegerProperty<ChatThreadBox>(
    _entities[2].properties[0],
  );

  /// See [ChatThreadBox.threadId].
  static final threadId = obx.QueryStringProperty<ChatThreadBox>(
    _entities[2].properties[1],
  );

  /// See [ChatThreadBox.title].
  static final title = obx.QueryStringProperty<ChatThreadBox>(
    _entities[2].properties[2],
  );

  /// See [ChatThreadBox.systemInstruction].
  static final systemInstruction = obx.QueryStringProperty<ChatThreadBox>(
    _entities[2].properties[3],
  );

  /// See [ChatThreadBox.chatFamily].
  static final chatFamily = obx.QueryStringProperty<ChatThreadBox>(
    _entities[2].properties[4],
  );

  /// See [ChatThreadBox.modelId].
  static final modelId = obx.QueryStringProperty<ChatThreadBox>(
    _entities[2].properties[5],
  );

  /// See [ChatThreadBox.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<ChatThreadBox>(
    _entities[2].properties[6],
  );

  /// See [ChatThreadBox.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<ChatThreadBox>(
    _entities[2].properties[7],
  );
}
